### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'total'

### ISSUE THREAD

**Issue by life-is-long-short** [josw123/dart-fss#1]
주피터 노트북에서 ```samsung_electronics.get_financial_statement(start_dt='20120101')``` 을 실행하면 tqdm 관련 에러메세지가 나옵니다.

**Comment by josw123** [comment]
pip install --upgrade tqdm 을 통해 tqdm 최신버전을 설치하신후 실행시켜 보시기 바랍니다.

**Comment by life-is-long-short** [comment]
업데이트 후 이슈가 해결됐습니다. 감사합니다.
