### ISSUE TITLE
xbrl 파일 추출 시 Spinner 이슈

### ISSUE THREAD

**Issue by baekspace88** [josw123/dart-fss#105]
현재 xbrl 파일 추출 시 화면에서 spinner가 돌고 있는데 이게 로그 파일에 함께 찍혀서 로그를 알아볼 수가 없습니다..
혹시 spinner를 제거하시거나 아니면 파라미터로 제거 여부를 선택하도록 개선이 가능할까요?
아니면 로그에서 제외하는 방법이 있는지 궁금합니다.

덕분에 좋은 라이브러리 잘 쓰고 있습니다. 감사합니다.

**Comment by josw123** [comment]
안녕하세요.
다음 버전에 spinner 및 progress bar 표시 선택이 가능한 옵션을 넣도록 하겠습니다.
좋은 의견 감사합니다.

**Comment by josw123** [comment]
extract 함수 및 extract_fs method에 progressbar 표시 관련 옵션(progressbar)을 추가하였습니다.
또한, 만약 xbrl 파일 단독 추출시 spinner를 off 하시려면 아래와 같이 하시면 됩니다. 
```python
 # Spinner disable
  import dart_fss as dart
  dart.utils.spinner.spinner_enable = False
```
