### ISSUE TITLE
cis 재무제표관련해서 문의드립니다.

### ISSUE THREAD

**Issue by lkhet3** [josw123/dart-fss#113]
먼저 개발해주신 개발자님께 감사말씀드립니다.
이번에 파이썬 공부하면서 dart-fss로 증권데이터를 가져올려고하는데
몇몇항목이 나오지않아서 문의드립니다.
불러오는 회사는 삼성전자 입니다.

아래는 코드내용입니다.

    cis_items=['ifrs-full_GrossProfit','dart_OperatingIncomeLoss','ifrs-full_ProfitLoss']
    bs_items=['ifrs-full_CurrentAssets','ifrs-full_NoncurrentAssets','ifrs-full_CurrentLiabilities','ifrs-full_NoncurrentLiabilities','ifrs-full_IssuedCapital','ifrs-full_Equity']
    cf_items=['ifrs-full_CashFlowsFromUsedInOperatingActivities','ifrs-full_CashFlowsFromUsedInInvestingActivities','ifrs-full_CashFlowsFromUsedInFinancingActivities']

        stockInfo = corp_list.find_by_corp_name(corpname,exactly=True,market='YK')[0]
        fs = stockInfo.extract_fs(bgn_de='20170101',fs_tp = ('cis','bs','cf'),lang='ko')

1. bgn_de로 2017년부터 지정했지만 2019년데이터부터 2021년데이터까지만 나옵니다.
2. Data_cis 시트탭 내용중 ifrs-full_GrossProfit 항목및 몇몇항목들이 나오질않습니다.(다른회사:씨아이에스 는 나오고있습니다.)
혹시 제가 다르게 설정해야할 부분이있을까요??

**Comment by josw123** [comment]
안녕하세요.

1. 삼성전자를 아래와 같이 추출한 경우 첨부된 파일과 같이 2014년부터 2021년까지의 데이터가 추출됩니다.
혹시 안되시는 경우 아래 fs_tp를 지정하지 않으시고 추출시도를 해보시기 바랍니다.
```python
fs = stockInfo.extract_fs(bgn_de='20170101')
``` 
[00126380_annual.xlsx](https://github.com/josw123/dart-fss/files/9089573/00126380_annual.xlsx)

2.   ifrs-full_GrossProfit 의 경우 cis가 아니라 is에 포함된 경우가 있습니다.(삼성전자의 경우에도 is에 있습니다.) 
이는 라이브러리에서 처리해주지 않고 회사에서 작성한 방식에 따라 추출되므로 확인하셔서 따로 처리해주셔야 됩니다.
