### ISSUE TITLE
거래정지종목

### ISSUE THREAD

**Issue by green7411** [josw123/dart-fss#117]
안녕하세요. 여러가지 동작을 실행시키던 중 거래정지 종목도 자료가 수집된 다는 것을 발견했는데요? 혹시 거래정지 종목을 스킵하는 방법이 있을까요?

**Comment by josw123** [comment]
안녕하세요.

[매매거래정지목록](https://kind.krx.co.kr/investwarn/tradinghaltissue.do?method=searchTradingHaltIssueMain)을 추출하여 처리하실수 있을것 같습니다.

관련 기능은 다음버전에 추가해드리도록 하겠습니다.

**Comment by 0x68756d8616e6f69664** [comment]
답변 감사합니다 ^^.
