### ISSUE TITLE
정정 전 보고서 추출 문의

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [josw123/dart-fss#122]
안녕하세요. 만들어주신 코드 잘 사용하고 있습니다.

재무제표 추출을 진행하다가 궁금한게 생겨서 문의드립니다. 제가 틀리지 않다면 정정 후 보고서로 추출이 진행되는 것 같습니다. 맞나요? 혹시 만약 그렇다면 **정정 전 보고서가 추출되도록 할 수 있는 방법**이 있을까요? 

*정정 후 보고서가 나오면 날짜에 따라 추출이 안 되는 경우가 발생합니다.

다시 한 번 감사드립니다.

**Comment by sukwoo1414** [comment]
https://dart-fss.readthedocs.io/en/latest/dart_search.html#dart
문서의 dart_fss.filings.search() 함수를 보시면 last_reprt_at 파라미터가 'N' 일 때 최종보고서가 아닌 보고서들도 검색됩니다. 저도 현재 정정전 보고서들이 정상적으로 검색되고있습니다.

**Comment by josw123** [comment]
안녕하세요.

현재 라이브러리에서는 재무제표 추출시에는 최종 보고서만을 이용하여 추출이 진행됩니다.
관련사항을 검토하여 정전 전 보고서에서도 추출이 가능하도록 옵션을 추가하도록 하겠습니다.
