### ISSUE TITLE
dart-fss import 시 SSLCertVerificationError 발생

### ISSUE THREAD

**Issue by nyanang** [josw123/dart-fss#124]
안녕하세요 

dart-fss를 install 하여 이용하고 싶은데, import 단계에서 계속 SSL 인증 관련 에러가 발생합니다.
이런 경우 어떻게 해결하면 될까요?

**Comment by josw123** [comment]
안녕하세요.

다음 링크의 블로그 내용 [Python Error - SSLCertVerificationError](https://coinpipe.tistory.com/171)을 참고하셔서 해결해 보시기 바랍니다.

만약 그래도 해결이 안되시면 실행 환경을 추가적으로 알려주시면 감사하겠습니다.
(OS 및 OS 버전, python 버전 및 실행환경 등)

**Comment by nyanang** [comment]
안녕하세요,

늦은 시간임에도 답변 주셔서 정말 감사합니다.
알려주신 방법대로 한 번 시도해보겠습니다.
감사합니다.

김송희 드림.
ᐧ

2022년 11월 6일 (일) 오후 10:57, Sungwoo Jo ***@***.***>님이 작성:
