### ISSUE TITLE
Error occurred during loading data. 해결방법 알려주시길 부탁드립니다.

### ISSUE THREAD

**Issue by 3coCCoo3** [josw123/dart-fss#127]
안녕하세요, 좋은 모듈때문에 정말 잘 사용하고 있는 일인입니다. 개발자분들께 다시한번 감사인사드립니다. 다름이아니라 최근 모듈 import 시 다음과 같은 error가 발생하고 있는데 관련해서 어떠한 정보도 찾을 수 없어 문의드립니다.
import dart_fss as dart 시 하기와 같은 에러가 발생합니다.
모듈 버전은 0.3.18이고 사용환경은 Window, Jupyternotebook 입니다. 

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Users\USER\anaconda3\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
(... 중략...)
FakeUserAgentError: Maximum amount of retries reached

**Comment by josw123** [comment]
안녕하세요.

fake-useragent 버전 문제로 구버전을 사용해서 발생하는 문제입니다.
아래와 같이 fake-useragent를 업데이트 해주시면 문제가 해결됩니다.
```bash
pip install -U fake-useragent 
```

**Comment by 3coCCoo3** [comment]
> 안녕하세요.
> 
> fake-useragent 버전 문제로 구버전을 사용해서 발생하는 문제입니다. 아래와 같이 fake-useragent를 업데이트 해주시면 문제가 해결됩니다.
> 
> ```shell
> pip install -U fake-useragent 
> ```

**Comment by 3coCCoo3** [comment]
오 감사합니다. 해결되었습니다.
