### ISSUE TITLE
dart-fss 설치 중 에러 발생

### ISSUE THREAD

**Issue by ckhpharm** [josw123/dart-fss#128]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

arelle

와 같은 에러 메세지가 뜨며 설치가 되지 않습니다
arelle 또한 설치가 안되던데
수정하실 계획이 있으실까요?

**Comment by josw123** [comment]
안녕하세요?

혹시 python은 어떤 버전을 사용하고 계신가요?
python 버전이 3.9까지는 아마 동작하는걸로 알고 있습니다만,
그 이상의 버전에서는 본 라이브러리가 제대로 동작하지 않습니다.
python 3.10 이상의 경우 코드 수정 및 테스트가 필요한 상황입니다.
요즘 제가 본업으로 인해 시간이 부족하여 시간나는 데로 테스트 후 문제가 없으면 배포하도록 하겠습니다.

**Comment by ckhpharm** [comment]
안녕하세요 답변 없을줄 알았는데
답변해주셔서 감사드립니다

제가 사용한 버전은 3.8.6 버전인데도 그러네요...

제가 초보인데 arelle 이라는 라이브러리가 설치가 안되서 그래 보입니다.

감사합니다

2022년 12월 5일 (월) 오후 1:50, Sungwoo Jo ***@***.***>님이 작성:

**Comment by josw123** [comment]
안녕하세요.

아래와 같이 arelle를 설치해 보시기 바랍니다.

```
pip install arelle
```

만약 오류가 발생한다면 오류 발생 정보를 모두 올려 주시면 감사하겠습니다.
추가적으로 설치 환경이나 OS 같은 것도 같이 올려주시면 감사하겠습니다.

**Comment by josw123** [comment]
안녕하세요.
방금 전 새로 배포된 dart-fss v0.4.0 버전을 설치해 보시기 바랍니다.
```bash
pip install dart-fss -U
```
의존성을 변경하였습니다.
