### ISSUE TITLE
BNK금융지주 AttributeError: ("'NoneType' object has no attribute 'tolist'"

### ISSUE THREAD

**Issue by coldtomatojuice** [josw123/dart-fss#129]
안녕하세요. 좋은 open source로 여러 사람들에게 큰 도움을 주고 계셔서 감사합니다. 

BNK금융지주에 대한 재무제표를 수집하기 위해 아래와 같은 에러가 발생하여 공유 드립니다. 
혹시 동일한 오류가 발생하시는지, 발생하신다면 이유는 어떤 것일지 문의 드립니다. 

Ubuntu 20.04 / Python 3.8.10 / dart-fss 0.3.18 

`fs = dart.fs.extract(corp_code='00858364', bgn_de='20200101', end_de='20220830', report_tp=['half'], cumulative=True, progressbar=True, separate=False)`

> Semiannual reports: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:07<00:00,  2.41s/report]
Traceback (most recent call last):
  File "load-dart-fs.py", line 108, in <module>
    load_fs()
  File "load-dart-fs.py", line 98, in load_fs
    fs = dart.fs.extract(corp_code='00858364', bgn_de='20200101', end_de='20220830', report_tp=['half'], cumulative=True, progressbar=True, separate=False)
  File "/home/wall/.local/lib/python3.8/site-packages/dart_fss/fs/extract.py", line 1475, in extract
    raise e
  File "/home/wall/.local/lib/python3.8/site-packages/dart_fss/fs/extract.py", line 1454, in extract
    label_df = select_cumulative(corp_code, label_df)
  File "/home/wall/.local/lib/python3.8/site-packages/dart_fss/fs/extract.py", line 1217, in select_cumulative
    ncolumns = concept_columns.tolist() + data_columns
AttributeError: ("'NoneType' object has no attribute 'tolist'", "An error occurred while fetching or analyzing {'rcp_no': '20200814002726', 'corp_code': '00858364', 'corp_name': 'BNK금융지주', 'stock_code': '138930', 'corp_cls': 'Y', 'report_nm': '반기보고서 (2020.06)', 'flr_nm': 'BNK금융지주', 'rcept_dt': '20200814', 'rm': ''}.")

**Comment by josw123** [comment]
안녕하세요, 답변이 많이 늦은 점 죄송합니다.

올려주신 문제는 XBRL concept이 없는 경우에 생기는 문제이므로 
수정하여 다음 버전에 반영되어 배포될 예정입니다.

감사합니다.

**Comment by jihunsong1993** [comment]
안녕하세요. 아래와 같은 코드를 사용하면서 위와 비슷한 에러가 생겼네요.

`corp = dart.get_corp_list().find_by_corp_name("이노진", exactly=True)[0]`
`corp.extract_fs(bgn_de='20200101', report_tp='annual',  lang='ko', separate=True, skip_error=True)`


위에서 언급해주신 것과 같이 아마 '이노진'이라는 회사가 XBRL이 없어서 생기는 문제인 것 같은데, 혹시 가능하시다면 위 커멘트 이후로 따로 업데이트 된 사항이 없는 것 같아서, 업데이트 한 번 요청 드려도 될까요? 

감사합니다.

**Comment by josw123** [comment]
내일 중으로 업데이트를 배포하도록 하겠습니다.
