### ISSUE TITLE
파미셀 extract_fs 에러 확인 부탁드립니다.

### ISSUE THREAD

**Issue by chahwon** [josw123/dart-fss#133]
이슈 항목 보니 extract_fs 관련 문의 가 많은데 혹시 관련 내용 소스내에서 직접 수정할수 있는
포인트가 있을까요? 
모든 종목에 대해서 이슈 처리가 힘드실것 같습니다.
사용자가 수정 할 수 있도록 처리가 되면 개발자님도 한결 수월 하실것 같습니다.

예외가 발생했습니다. RuntimeError
('Could not find an annual report', 'Unexpected Error')

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "D:\DEV\Python_project\FinancialStatements_Analysis.py", line 16, in <module>
    fs = company.extract_fs(bgn_de='20120101', end_de='20210501', report_tp='quarter', separate=True)

**Comment by josw123** [comment]
안녕하세요.

DART에 공시된 회사명 '파미셀'이 2개가 있습니다.
(완전 동일한 회사명입니다)

아래와 같이 하나는 유가증권에 상장된 기업이며 하나는 아닌 기업입니다.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10247774/217270590-47fc8683-3124-4e78-a36a-998cb979cc70.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/10247774/217270682-352c8a70-8365-4cde-83b3-73caf0aea9d4.png">

유가증권에 상장된 기업의 경우 올래주신 코드로 문제가 발생하지 않으며, 비상장기업의 경우 동일한 오류가 발생하는 것을 보았을때, 아마 비상장기업에서 추출을 시도하신것으로 생각됩니다.  (비상장기업에서 발생하는 오류는 아무런 공시가 없기 때문에 발생하는 오류이므로, 정상적인 오류 발생입니다)

corp_code가 00145163 이며 stock_code가 005690 인지 확인하셔서 다시한번 추출해 보시기 바랍니다.


재무제표 추출과 관련 소스코드는 [dart_fss/fs/extract.py](https://github.com/josw123/dart-fss/blob/master/dart_fss/fs/extract.py) 에서 내부에 대부분 위치해 있습니다.

다만 XBRL 추출과 관련된 내용들은 [dart_fss/xbrl](https://github.com/josw123/dart-fss/tree/master/dart_fss/xbrl)에 따로 존재합니다. 

추출과 관련된 오류 발생시 이 두부분에서 대부분 문제가 발생하오니 이 부분을 수정하셔서 사용하시면 되겠습니다. 또한, 수정한 부분을 커밋해주시면 프로젝트 유지보수에 많은 도움이 되겠습니다. 

좋은 의견 주셔서 감사합니다!

**Comment by chahwon** [comment]
답변 주셔서 감사합니다. 파이썬 같은 경우 필요시 잠깐씩 확인하며 디버깅으로 값만 보는 수준이라 ..
이 참에 제대로된 공부좀 해 봐야 할 듯 합니다. 다시 한번 감사합니다.
