### ISSUE TITLE
일부 기업 재무상태표 가져오기 오류 추가

### ISSUE THREAD

**Issue by paladinz67** [josw123/dart-fss#14]
안녕하세요, 
일부 기업의 재무상태표 가져오기에서 추가 오류가 발견되었습니다. ㅠㅠ
제가 전체 기업의 재무상태표를 모두 수집하다 보니 여러 유형의 오류를 발견하는 것 같습니다.

유형 1)
- 별도 재무상태표 추출 시 발생
- RuntimeError: An error occurred while fetching or analyzing {'crp_cls': 'K', 'crp_nm': '파나진', 'crp_cd': '046210', 'rpt_nm': '사업보고서 (2010.12)', 'rcp_no': '20110331002486', 'flr_nm': '파나진', 'rcp_dt': '20110331', 'rmk': '', 'pages': 'Not loaded'}.
- 발생 기업: 파나진, 와이오엠, 한농화성, 한화갤러리아타임월드 등

유형 2)
- 연결 재무상태표 추출 시 발생
- RuntimeError: An error occurred while fetching or analyzing {'crp_cls': 'K', 'crp_nm': '뉴프라이드', 'crp_cd': '900100', 'rpt_nm': '사업보고서 (2017.12)', 'rcp_no': '20180430000663', 'flr_nm': '뉴프라이드', 'rcp_dt': '20180430', 'rmk': '연', 'xbrl_url': 'http://dart.fss.or.kr/pdf/download/ifrs.do?rcp_no=20180430000663&dcm_no=6135023&lang=ko', 'pages': 'Not loaded'}.
- 발생 기업: 뉴프라이드, 대우건설, 영원무역 등

유형 3)
- 연결 재무상태표 추출 시 발생
- AttributeError: 'NoneType' object has no attribute 'columns'
- 발생 기업: 두원석재, 나눔테크, 이노벡스 등

각 유형 별 상세 error 로그는 첨부 파일을 참조하십시오.

감사합니다.
[파나진_error_log.txt](https://github.com/josw123/dart-fss/files/3440790/_error_log.txt)
[뉴프라이드_error_log.txt](https://github.com/josw123/dart-fss/files/3440791/_error_log.txt)
[두원석재_error_log.txt](https://github.com/josw123/dart-fss/files/3440794/_error_log.txt)

**Comment by josw123** [comment]
로그를 확인해 보고 버그를 수정하도록 하겠습니다.
감사합니다.

**Comment by paladinz67** [comment]
v0.2.0 release 감사드립니다.
class가 많이 바뀌었지만 사용하기엔 더 편리해 진 것 같습니다.
항상 변치 않는 지원에 감사 드립니다.
