### ISSUE TITLE
XBRL이 정상적으로 파싱되지 않는 추가 케이스

### ISSUE THREAD

**Issue by sukwoo1414** [josw123/dart-fss#140]
저번 #137 에 이어 추가적으로 XBRL이 정상적으로 파싱되지 않는 케이스를 찾았습니다.
{'Code': '096870', 'Settlement': '201203', 'Disclosure': '20120511', 'FS': 'cis'}
{'Code': '096870', 'Settlement': '201203', 'Disclosure': '20120515', 'FS': 'cis'}
{'Code': '096870', 'Settlement': '201206', 'Disclosure': '20120814', 'FS': 'cis'}
{'Code': '096870', 'Settlement': '201206', 'Disclosure': '20121009', 'FS': 'cis'}
{'Code': '096870', 'Settlement': '201209', 'Disclosure': '20121112', 'FS': 'cis'}
이번에도 모두 별도 재무제표이며, #137 과 마찬가지로 공시보고서와 XBRL 원문은 정상적이나, analyze_xbrl()의 결과가 비정상인 케이스입니다.
모두 0.4.3으로 확인한 결과이며, 0.4.3에서 새로 생겨난 문제는 아니고 이전부터 있었던 문제입니다.
감사합니다.

**Comment by josw123** [comment]
확인해 보도록 하겠습니다

**Comment by josw123** [comment]
유효한 데이터가 1개 미만인 경우에만 열을 삭제해야 하지만, 
1개 이하로 설정되어 있어서 1개일 때도 삭제 되는 문제가 발생했습니다.

다음 버전에서는 수정된 파일을 배포하도록 하겠습니다.
