### ISSUE TITLE
fs_extract에서의 오류

### ISSUE THREAD

**Issue by jhsung0607** [josw123/dart-fss#141]
신한라이프생명보험의 20230315 사업보고서를 읽어올 때
/usr/local/lib/python3.10/dist-packages/dart_fss/fs/extract.py:392: RuntimeWarning: TypeError('expected string or bytes-like object') : 1.0
  warnings.warn(warnings_text, RuntimeWarning)
이런 알림이 한두개가 아니라 여러개가 뜹니다.
정작 확인해보면 제대로 크롤링해오긴 하지만, 다른건 다 안뜨는데 얘만 떠서 이상하다고 느꼈습니다.

케이비라이프생명보험의 20230316의 사업보고서를 읽어올 때
/usr/local/lib/python3.10/dist-packages/dart_fss/fs/extract.py:266: RuntimeWarning: Date data length does not match table header.So last date was set using last data(19000101). 
  warnings.warn(warnings_text, RuntimeWarning)
이런 알림이 뜹니다.

또한 흥국화재의 20230316 사업보고서를 읽어올 때
TypeError: ("'NoneType' object is not iterable", "An error occurred while fetching or analyzing {'rcp_no': '20230316001454', 'corp_code': '00103176', 'corp_name': '흥국화재', 'stock_code': '000540', 'corp_cls': 'Y', 'report_nm': '사업보고서 (2022.12)', 'flr_nm': '흥국화재', 'rcept_dt': '20230316', 'rm': ''}.")
이런 에러가 뜨는데, 비슷한 오류 확인해보니까 html table 태그 때문이라고 하는 내용을 보았습니다.
![image](https://user-images.githubusercontent.com/75656845/236728345-d37f0106-1839-4fe5-bf7d-d136deea55fe.png)
하지만 다른 테이블이랑 다른거 없어보이는데 왜 안되는걸까요?

마지막으로 만들어주신 라이브러리 잘 사용하고 있어서 감사드리고싶습니다. 감사합니다.

**Comment by josw123** [comment]
안녕하세요.

신한라이프생명보험의 2023.03.15. 사업보고서의 경우 테스트 해본결과 dart-fss v0.4.3에서는 별다른 경고문이 뜨지 않습니다.
혹시 관련 코드 및 dart-fss 버전, 그리고 운영체제 등을 알려 주시면 감사하겠습니다.

케이비라이프생명보험 및 흥국화재의 오류는 관련 코드 검토 후 추가 답변 드리도록하겠습니다.

**Comment by jhsung0607** [comment]
저는 코랩에서 dart-fss v0.4.3을 사용하고있습니다.
감사합니다.

**Comment by josw123** [comment]
안녕하세요.

코랩에서 신한라이프생명보험의 2023.03.15. 사업보고서의 경우 테스트 해본결과 올려주신 내용과 같은 오류가 발생하지 않습니다. 일시적인 오류로 생각이 됩니다.

**케이비라이프생명보험의 20230316의 사업보고서**의 경우 "재무상태표", "포괄손익계산서", "자본변동표", "현금흐름표"가 공시되어 있고, 이중 dart-fss에서는 자본변동표를 제외한 "재무상태표", "포괄손익계산서", "현금흐름표"를 추출하게 됩니다. 그런데 dart-fss v0.4.3.을 이용하여 추출하게 되면 손익계산서 까지 추출하게 되는데 **이는 아래와 같이 보고서에  3) 재무영향평가 항목에 손익계산서가 작성되어 있기 때문입니다.** 이는 일반적인 재무제표 양식이 아니며, 이로 인해 발생하는 문제로 생각됩니다. 다음 버전에서 관련 문제를 수정해보도록 하겠습니다.

![image](https://github.com/josw123/dart-fss/assets/10247774/d79108fe-d8f9-4f23-ac96-04965a722e01)

흥국화재의 20230316 사업보고서의 경우에도 케이비라이프생명보험과 비슷한 문제가 발생한 것으로 파악되며, 다음버전에 수정하도록 하겠습니다.
