### ISSUE TITLE
값이 콜할때 마다 다르게 리턴됩니다.

### ISSUE THREAD

**Issue by shinhwas** [josw123/dart-fss#15]
안녕하세요. ShinhwaS입니다.
별도 자본변동표에 dart_EquityAtBeginningOfPeriod [2018-09-01,2018-11-30]별도재무제표의 값이 콜할때 마다 다르게 리턴됩니다.

report_no: '20190111000477'
테이블을 파일로 첨부합니다.

[별도_기초자본_오류.txt](https://github.com/josw123/dart-fss/files/3474086/_._.txt)

**Comment by josw123** [comment]
안녕하세요.

확인해보니 title에 이익잉여금, 자본금 등 세부정보가 제거된 상태로 출력되어 동일한  "[2018-09-01,2018-11-30]별도재무제표" 이름으로 출력되어서 그런것 같습니다.

이 문제는 다음 업데이트 때 수정하도록 하겠습니다.
