### ISSUE TITLE
CJ 분기 보고서 추출이 안 되는데

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [josw123/dart-fss#152]
# 전체 회사 리스트
corplist = get_corp_list()

# 주식 코드로 dart 코드 찾기
corpinfo = corplist.find_by_stock_code('001040')

fs = corpinfo.extract_fs(bgn_de = '20211201', fs_tp = ['is'], report_tp = ['quarter'], last_report_only = False)

위와 같이 실행하니 마지막 줄에서

("'NoneType' object is not iterable", "An error occurred while fetching or analyzing {'rcp_no': '20220516002143', 'corp_code': '00148540', 'corp_name': 'CJ', 'stock_code': '001040', 'corp_cls': 'Y', 'report_nm': '분기보고서 (2022.03)', 'flr_nm': 'CJ', 'rcept_dt': '20220516', 'rm': ''}.")

라고 나옵니다.

이번에도 무슨 옵션을 잘 못 적은 것일까요?

**Comment by josw123** [comment]
안녕하세요.

아래와 같이 동일한 코드로 돌려본 결과 문제 없이 동작하는 것을 확인하였습니다.
```python
import sys
import dart_fss as dart

print(f"Python: {sys.version}")
print(f"Dart-fss version: {dart.__version__}")

corplist = dart.get_corp_list()
corpinfo = corplist.find_by_stock_code('001040')
fs = corpinfo.extract_fs(bgn_de = '20211201', fs_tp = ['is'], report_tp = ['quarter'], last_report_only = False)

```

혹시 환경이 어떻게 되실까요?

Python 버전, os 종류, dart-fss 버전 등을 알려주시면 추가로 테스트 진행해보도록 하겠습니다.

**Comment by WonSeokChoi-Unicorn** [comment]
> 안녕하세요.
> 
> 아래와 같이 동일한 코드로 돌려본 결과 문제 없이 동작하는 것을 확인하였습니다.
> 
> ```python
> import sys
> import dart_fss as dart
> 
> print(f"Python: {sys.version}")
> print(f"Dart-fss version: {dart.__version__}")
> 
> corplist = dart.get_corp_list()
> corpinfo = corplist.find_by_stock_code('001040')
> fs = corpinfo.extract_fs(bgn_de = '20211201', fs_tp = ['is'], report_tp = ['quarter'], last_report_only = False)
> ```
> 
> 혹시 환경이 어떻게 되실까요?
> 
> Python 버전, os 종류, dart-fss 버전 등을 알려주시면 추가로 테스트 진행해보도록 하겠습니다.

Python 버전 : Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]

os 종류 : 윈10 프로 21H2

dart-fss 버전 : Dart-fss version: 0.4.2

입니다.

**Comment by josw123** [comment]
안녕하세요. 

DART  사이트 업데이트로 인해 dart-fss 버전을 최신버전(0.4.7)으로 업데이트 하셔야 정상적으로 동작합니다.

아래와 같이 터미널에서 업데이트를 진행하셔서 다시 실행해 보시기 바랍니다
```bash
pip install -U dart-fss
```

**Comment by WonSeokChoi-Unicorn** [comment]
> 안녕하세요.
> 
> DART 사이트 업데이트로 인해 dart-fss 버전을 최신버전(0.4.7)으로 업데이트 하셔야 정상적으로 동작합니다.
> 
> 아래와 같이 터미널에서 업데이트를 진행하셔서 다시 실행해 보시기 바랍니다
> 
> ```shell
> pip install -U dart-fss
> ```

오~~~됩니다.
해법 알려주셔서 감사합니다.
