### ISSUE TITLE
코스피와 코스닥 상장 기업 리스트만 반환할 수 있나요?

### ISSUE THREAD

**Issue by InvestingCoder** [josw123/dart-fss#153]
코스피와 코스닥 상장 기업 리스트만 반환하여
반복문을 돌려 모든 기업의 실적을 가져오려 합니다.

corp_list = dart.get_corp_list()

all_corp_list = dart.api.filings.get_corp_code()
df_all_corp_list = pd.DataFrame(all_corp_list)
df_public_corp_list = df_all_corp_list[df_all_corp_list['stock_code'].notnull()]

이렇게 stock_code가 없는 기업을 제거 했는데요.
기타법인들이 남아있더라구요.

corp_list = dart.get_corp_list()로는 기타법인의 구별은 되어있지 않은것으로 보이는데 혹시 방법이 있을까요?

**Comment by josw123** [comment]
안녕하세요.
아래 코드와 같이 하시면 코스피와 코스닥 상장 기업 리스트만 반환됩니다.

```python
import dart_fss as dart

corp_list = dart.get_corp_list()
# 코스닥과 코스피 상장된 회사 리스트 반환
# 'Y': 코스피, 'K': 코스닥, 'N': 코넥스, 'E': 기타
yk_corp_list = crop_list.find_by_corp_name('', market='YK')
```

감사합니다.

**Comment by InvestingCoder** [comment]
감사합니다. 도움 많이 되었습니다.
