### ISSUE TITLE
중복회사 오류

### ISSUE THREAD

**Issue by tejung2** [josw123/dart-fss#154]
안녕하세요~ 너무 잘 쓰고 있습니다 감사합니다. 새해복 많이 받으세요!

다름이 아니라, 비상장회사 중복회사의 경우, 데이터를 가져올 수 없는 오류가 있어서 문의드립니다.

검색 회사는 현대엔지니어링 입니다.(비상장 ,기타법인)
DART에서 조회되는 회사만 3개라서 데이터 호출을 못하지 않는가 추측됩니다.

이런 경우에는 어떤 방법을 통해 데이터 호출을 할 수 있을까요??!

**Comment by josw123** [comment]
안녕하세요.

다음과 같이 검색하시면 3개의 회사가 모두 검색되며,
그 중에 원하시는 회사를 조회하시면 되겠습니다.

```python
import dart_fss as dart
corps = corp_list.find_by_corp_name('현대엔지니어링')

print(corps)
# [[01229727](주)현대엔지니어링, [00349927]현대엔지니어링(주), [01465666](주)현대엔지니어링]

# 위와 같이 corp_code가 모두 다르기 때문에 이중 두번째 회사를 선택하는 경우
corp = corps[1]

# 회사 정보 로딩
corp.load()
# 회사 정보 출력
print(corp.info)

fs = corp.extract_fs(bgn_de='20230101')
```
감사합니다.
조성우 드림.

**Comment by tejung2** [comment]
감사합니다 !!

덕분에 호출 완료하여 데이터까지 뽑았습니다 ㅎㅎㅎ 그런데 결과를 보면 아래와 같이
군데군데 빠져있는 데이터가 있네요. 이거는 Dart의 시스템 데이터를 그대로 끌고 오는 것이니 시스템 데이터 자체가
이렇게 군데군데 빠져있는 거라고 봐야할까요??


![캡처](https://github.com/josw123/dart-fss/assets/152825289/2feb6b38-8da5-4bfd-92a6-4ed1cdfe1fa1)

**Comment by josw123** [comment]
상장된 회사의 경우 xbrl파일이 제공되기때문에 높은 정확도가 보장됩니다.
이에 반하여, 비상장회사의 경우 xbrl 파일이 제공되지 않기때문에 web page 기반으로 데이터를 추출하게 되며 상대적으로 재무제표 기제 양식이 엄격하지 않기때문에 일부 오류가 있을 수 있습니다.

비상장사의 경우 빠진 내용이 실제로 빠져 있는경우가 많겠지만 혹시 모르니 공시된 정보를 확인해보시는것을 추천드립니다.
