### ISSUE TITLE
dart-fss v0.4.8 '유안타증권' 추출 오류

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [josw123/dart-fss#164]
안녕하세요. 기존 버전부터 잘 사용하고 있고 업데이트가 일어났는지 가끔 확인하며 잘 따라가고 있습니다.

이번에 0.4.7에서 0.4.8로 업데이트 하면서 새로 찾은 문제인데요?
유안타증권 (003470)을 재무제표를 추출하는데 'cis' , 'cf' 키워드로 추출되는 구간이 'cis' 의 경우 
'20220101'  'cf'의 경우 '20230101' '20220101' 구간이 존재합니다. 이는 기존 '시작구간-종료구간' 과 다른 형태인데요?
혹시 원인을 알 수 있을까요?? 비교는 '003490'과 하였습니다. (어느 것과 비교해도 상관 없음)

감사합니다.

**Comment by josw123** [comment]
안녕하세요.

올려주신 내용을 확인해보니, HTML에서 일자 추출시 발생하는 버그 인것 같습니다.
아래와 같이 공시되어 있으므로 이를 추출하는 과정에서 버그가 발생하는 것으로,
수정을 진행하도록 하겠습니다.

![image](https://github.com/josw123/dart-fss/assets/10247774/b2b5a9ad-ed55-41cd-8ff7-193ac7a8755a)

**Comment by 0x68756d8616e6f69664** [comment]
빠른 해결 감사드립니다.
