### ISSUE TITLE
음수가 양수로 표현됩니다.

### ISSUE THREAD

**Issue by ISeeTheFuture** [josw123/dart-fss#166]
네이버(00266961) 3분기 보고서 현금흐름표, 간접법 - 연결
element_id : "entity00266961_udf_CF_20225423444564_CashFlowsFromUsedInInvestingActivities"
item_nm : 당기손익-공정가치 측정 금융자산의 취득

위 값은 공시를 보면 음수이지만, dart_fss로 받으면 양수로 나옵니다. 계정별로 weight란 값을 반영해야 하는 것으로 보입니다.

XBRL 원본(*_cal.xml 파일)에도 weight가 들어있는 것이 확인됩니다.
혹시 이 weight가 추출되고 있나요?

____

그리고 사족이지만 spinner 끌 수 있었으면 좋겠습니다. log에 남아버려서요ㅠㅠ

**Comment by josw123** [comment]
안녕하세요.

올려주신 내용과 같이 weight가 반영되지 않는 문제가 있어 이를 다음버전에 수정하도록 하겠습니다.
spinner 끄는 기능도 추가하도록 하겠습니다.

**Comment by ISeeTheFuture** [comment]
확인해보니, 양수 음수 표현에 관련된 것이 weight 뿐 아니라 negated라는 속성도 있는 것 같습니다.
좀 더 자세한 검토가 필요해 보입니다.

**Comment by josw123** [comment]
확인 후 방법을 수정하였습니다.
알려주신 바와 같이 preferred label 설정에 따라 음수처리 하도록 알고리즘을 변경하였습니다.
