### ISSUE TITLE
concept_id 대소문자 구분이 안되어서 값을 잘못 가져오는 오류가 있습니다.

### ISSUE THREAD

**Issue by ISeeTheFuture** [josw123/dart-fss#168]
케이스1
기업명 : 파이버프로
corp_code : 01513440
대상 재무제표 : 현금흐름표 별도
대상 보고서 : 2023년 3분기 보고서
계정명 : 유동성장기대여금의 증가 / 장기대여금의 증가
관련 공시 : https://opendart.fss.or.kr/xbrl/viewer/main.do?rcpNo=20231113000159
관련 concept_id : entity01513440_IncreaseInLongTermLoansGrossOfCashFlowsFromUsedInInvestingActivities

케이스2
기업명 : 케이씨씨글라스
corp_code : 01428203
대상 재무제표 : 재무상태표 연결
대상 보고서 : 2023년 3분기보고서
계정명 : 매출채권 / 기타채권
관련 공시 : https://opendart.fss.or.kr/xbrl/viewer/main.do?rcpNo=20231114002408
관련 concept_id : entity01428203_CurrentTradeReceivablesOfCurrentAssets

케이스3
기업명 : 현대자동차
corp_code : 00164742
대상 재무제표 : 포괄손익계산서 연결
대상 보고서 : 사업보고서
계정명 : 보통주 희석주당이익 / 1우선주 희석주당이익
관련 공시 : https://opendart.fss.or.kr/xbrl/viewer/main.do?rcpNo=20240313001451
관련 concept_id : entity00164742_DilutedearningslosspershareOfDilutedEarningsLossPerShare

케이스1 을 예시로 설명
문제점 :
"entity01513440_IncreaseInLongTermLoansGrossOfCashFlowsFromUsedInInvestingActivities"와
"entity01513440_IncreaseInLongtermLoansGrossOfCashFlowsFromUsedInInvestingActivities"가 구분이 안되고 있음.
두 id는 Term, term 으로 대소문자만 다른데, 두 계정의 값이 각기 올바르게 들어오지 않습니다.

**Comment by josw123** [comment]
안녕하세요.

올려주신 버그는 확인하였으며, 다음 버전에 수정된 버전이 배포될 예정입니다.
