### ISSUE TITLE
손익계산서의 일부 값 누락

### ISSUE THREAD

**Issue by goldragoon** [josw123/dart-fss#17]
아래와 같은 코드를 실행하면,
```
import dart_fss as dart
dart.dart_set_api_key(api_key='~')
crp_list = dart.get_crp_list()
zezi = crp_list.find_by_name('한국제지')
fs_annual = zezi.get_financial_statement(start_dt='20140101', fs_tp='ci')
```

다음과 같이 당기순이익의 일부 값에 nan이 들어가 있는 것을 확인하실 수 있습니다.
![image](https://user-images.githubusercontent.com/2537598/63506869-628c7980-c511-11e9-9dce-9e945f35aa7f.png)

그러나 DART에서 직접 확인해보면, 실제로는 값이 존재하더라구요.
![image](https://user-images.githubusercontent.com/2537598/63506979-a1baca80-c511-11e9-8435-49bcedaee80c.png)

혹시 제가 작성한 코드 상에 문제가 있을까요?
아니라면, 제가 버그를 해결하고 pull request를 올려보겠습니다.

좋은 라이브러리 개발해주셔서 감사합니다.

**Comment by josw123** [comment]
안녕하세요.
작성하신 코드에는 문제가 없습니다.
현재 공개된 버전의 경우 확인하신 것과 같이 버그가 있습니다.

그런데 현재 v0.2.0을 작성중에 있으며, 재무제표 추출과 관련된 소스코드 부분이 많이 수정되었습니다.
v0.1.x 까지는 사업보고서의 본문에서 재무제표를 추출 하였다면
v0.2.0에서는 사업보고서에 첨부된 감사보고서를 이용하여 데이터를 추출할 예정입니다.
올려주신 문제 또한 어느정도 수정된 상태입니다.

조만간 소스코드를 업로드할 예정이오니 그 때가지만 가다려주시면 감사하겠습니다.
버그 및 피드백 남겨주신점 감사합니다.

![image](https://user-images.githubusercontent.com/10247774/63510488-adaa8a80-c519-11e9-8fc7-3982e6587bec.png)

**Comment by goldragoon** [comment]
@josw123 빠른 답변 감사합니다.
혹여라도 도울 것이 있으면 말씀해주세요!

**Comment by josw123** [comment]
네 그렇게 하도록 하겠습니다.
감사합니다 ㅎㅎ
