### ISSUE TITLE
재무제표 추출 문의

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [josw123/dart-fss#177]
안녕하세요. dart-fss를 요긴하게 사용하는 유저입니다.
정말 좋은 툴을 제공해주셔서 감사합니다. 

사용하다 보니 이전에 발견하지 못 했던 문제를 분석하게 됬는데요.
아래와 같은 코드로 재무제표 추출 시 아래 처럼 데이터가 누락된 모습이 있습니다. (ex: 20230630 재무제표)
코드를 같이 첨부하오니 분석 가능하실까요?

"이미지"
![image](https://github.com/user-attachments/assets/dadef971-ba98-41ee-8b1f-b1039894c12e)

"코드"
import dart_fss as dart

# Open DART API KEY 설정
api_key='생략'
dart.set_api_key(api_key=api_key)

# DART 에 공시된 회사 리스트 불러오기
corp_list = dart.get_corp_list()

# 삼성전자 검색
samsung = corp_list.find_by_corp_name('앱코', exactly=True)[0]

# 2012년부터 연간 연결재무제표 불러오기
fs = samsung.extract_fs(bgn_de='20230101', report_tp='quarter')

# 재무제표 검색 결과를 엑셀파일로 저장 ( 기본저장위치: 실행폴더/fsdata )
fs.save()

**Comment by josw123** [comment]
안녕하세요.

혹시 dart-fss 버전은 얼마를 사용하신 것인가요?
```python
import dart_fss as dart
print(dart.__version__)
```

v0.4.10 기준으로 올려주신 결과를 테스트해보니 연결재무제표 미포함으로 인한 오류만 발생하였습니다.(NotFoundConsolidated 오류)

또한 사업보고서를 확인해 보니 아래와 같이 종속회사 청산으로 인한 개별재무제표만 작성되었다고 나와있었습니다.
![image](https://github.com/user-attachments/assets/c03278c2-ae42-4cdf-b0e5-58b0156fb9e8)

추가적으로 개별재무제표 추출시에는 별다른 문제 없이 아래 첨부된 파일과 같이 추출이 되는 것 같습니다.

[01207716_quarter.xlsx](https://github.com/user-attachments/files/16754230/01207716_quarter.xlsx)

dart-fss 버전 및 OS 등을 기재해주시면 추가적으로 테스트 진행해보도록 하겠습니다.

**Comment by 0x68756d8616e6f69664** [comment]
가장 최신 버전입니다. 애당초 제무재표 문제였군요. 감사합니다.
