### ISSUE TITLE
[연결차단 문의] stock_totqy_sttus 함수

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [josw123/dart-fss#179]
안녕하세요?
stock_totqy_sttus 함수를 사용해서 주식 data를 추출하다보면 랜덤하게 연결이 차단되서 불편을 겪는 경우가 있는데요?
아래 set.delay = 0.5로 수정해도 같은 상황이라 혹시 또 다르게 접근할 수 있는 방법이 있을까요?
주식의 총 수를 추출하고 싶어서 사용하는 함수 입니다!

# 분당 1000회 이상 자체적으로 24시간 IP차단
        # IP 차단 방지 위해 delay 0.1s -> 0.2s
        self.delay = 0.2

[현재 사용하는 코드]
samsung = corp_list.find_by_stock_code("005930", include_trading_halt=False)
samsung_num = dart.api.info.stock_totqy_sttus(samsung.corp_code, "2023", "11011", api_key=api_key)

**Comment by josw123** [comment]
안녕하세요.

DART 서버 측 에서 연결을 차단하는 상황에서는 proxy를 통해서 IP rotation을 진행하시는 방법밖에 없을 것으로 생각됩니다.
(또한 IP rotation시 API_KEY 또한 rotation 해주어야 될 것으로 생각됩니다.)

**Comment by 0x68756d8616e6f69664** [comment]
답변 감사합니다. 제가 이해한게 맞다면 인터넷 망이 IP rotation 수 만큼 필요하다는 것 일까요? 만약 현재 한개의 인터넷만 사용하면 불가능인가요? 검색해보니 임의의 수의 IP를 사용해야 하는 것 처럼 보여서요!

**Comment by josw123** [comment]
다중망을 구성해서도 가능하지만, [AWS 등을 활용](https://gist.github.com/6mini/44ff7413f1b88bdb377e8f2ca731d5f5)하여 IP를 변경해가면서 크롤링하는 방법들도 있습니다. 관련 사항들은 구글을 찾아보시면 다양한 사례들이 있으니, 한번 확인해보시는 편이 좋을 것 같습니다.

**Comment by 0x68756d8616e6f69664** [comment]
찾아봐서 배워보겠습니다. 감사합니다!
