### ISSUE TITLE
분기, 반기 리포트 조회시 NoDataReceived 에러 

### ISSUE THREAD

**Issue by kkkim2015** [josw123/dart-fss#181]
안녕하세요. 먼저 좋은 라이브러리를 만들어 주셔서 감사하다는 말씀 올리고 싶습니다.

이 라이브러리를 처음 사용 중에 아래와 같은 에러가 떠서 도움 요청 드립니다. 

아래는 제가 쓴 코드입니다. 
`fs = dart.fs.extract(corp_code= '01411434', bgn_de='20240101', end_de='20241027',lang='ko', report_tp = 'quarter', separate = True, separator=True, last_report_only= True)`

카카오엔터프라이즈의 corp_code를 그대로 넣어서 데이터를 가지고 오려고 합니다. 

본 코드를 사용하면 아래와 같은 에러가 뜹니다. 

> Traceback (most recent call last):
  File "C:\Users\lisa5\getReport.py", line 69, in <module>
    getReport()
  File "C:\Users\lisa5\getReport.py", line 60, in getReport
    fs = dart.fs.extract(corp_code= '01411434', bgn_de='20240101', end_de='20241027',lang='ko', report_tp = 'quarter', separate = True, separator=True, last_report_only= True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\dart_fss\fs\extract.py", line 1552, in extract
    raise e
  File "C:\Python312\Lib\site-packages\dart_fss\fs\extract.py", line 1476, in extract
    reports = search_filings(corp_code=corp_code, bgn_de=bgn_de, end_de=end_de,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\dart_fss\filings\search.py", line 51, in search
    resp = search_filings(corp_code=corp_code,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\dart_fss\api\filings\search_filings.py", line 81, in search_filings
    check_status(**dataset)
  File "C:\Python312\Lib\site-packages\dart_fss\errors\checker.py", line 47, in check_status
    raise err(msg)
dart_fss.errors.errors.NoDataReceived: ('조회된 데이타가 없습니다.', "An error occurred while fetching or analyzing {'rcp_no': '20240401001039', 'corp_code': '01411434', 'corp_name': '카카오엔터프라이즈', 'stock_code': '', 'corp_cls': 'E', 'report_nm': '감사보고서 (2023.12)', 'flr_nm': '삼정회계법인', 'rcept_dt': '20240401', 'rm': ''}.")

저는 bgn_de를 20240101로 설정했는데 2023.12 리포트를 못 가지고 와서 에러가 나는 것 같아 문의드립니다. 

report_tp를 바꾸면서 여러 시도를 해보았는데 report_tp가 'annual' 일때는 정상 작동, 'quarter' 혹은 'half'로 바꾸면 에러가 나는 것도 확인했습니다. 

혹시나 해서 separate= True와 False 각각 넣어서 시도했지만 같은 에러가 뜹니다  

도움 부탁드립니다.

**Comment by josw123** [comment]
안녕하세요.

카카오엔터프라이즈의 경우 위에 올려주신 검색조건으로 DART에서 검색해보면 아래와 같이 총 10개의 공시만 검색이 됩니다.

<img width="471" alt="image" src="https://github.com/user-attachments/assets/08f037f1-e236-4170-9c8c-ad4dd725673e">

그중에서 "연결감사보고서", "감사보고서"를 통해 연간재무제표는 추출가능하나, 이외의 반기 및 분기 공시는 따로 하지 않았기 때문에 관련 자료가 없습니다.

그러므로 올려주신 오류(NoDataReceived / 조회된 데이터가 없습니다)의 경우 올바르게 작동한 것으로 생각되며,
report가 quarter나 half일때에는 위의 오류가 발생하는 것이 정상입니다.

**Comment by kkkim2015** [comment]
안녕하세요. 답변 감사드립니다. 

카카오엔터프라이즈의 경우 반기, 분기 리포트가 없는 것을 확인했습니다. 
하지만 아래와 같은 삼성전자 에서도 같은 에러가 나는데 확인 한번 부탁드려도 될까요?

![image](https://github.com/user-attachments/assets/605a9eab-1fa3-46d9-8e15-97cec0570a8d)

`fs = dart.fs.extract(corp_code= '00258999', bgn_de='20240101', end_de='20241030',lang='ko', report_tp = 'half', separate = True, separator=True)`

> Traceback (most recent call last):
File "C:\Users\lisa5\getReport.py", line 69, in
getReport()
File "C:\Users\lisa5\getReport.py", line 60, in getReport
fs = dart.fs.extract(corp_code= '00258999', bgn_de='20240101', end_de='20241030',lang='ko', report_tp = 'half', separate = True, separator=True, last_report_only = True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\dart_fss\fs\extract.py", line 1552, in extract
raise e
File "C:\Python312\Lib\site-packages\dart_fss\fs\extract.py", line 1476, in extract
reports = search_filings(corp_code=corp_code, bgn_de=bgn_de, end_de=end_de,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\dart_fss\filings\search.py", line 51, in search
resp = search_filings(corp_code=corp_code,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\dart_fss\api\filings\search_filings.py", line 81, in search_filings
check_status(**dataset)
File "C:\Python312\Lib\site-packages\dart_fss\errors\checker.py", line 47, in check_status
raise err(msg)
dart_fss.errors.errors.NoDataReceived: ('조회된 데이타가 없습니다.', "An error occurred while fetching or analyzing {'rcp_no': '20240328001286', 'corp_code': '00258999', 'corp_name': '삼성전자서비스', 'stock_code': '', 'corp_cls': 'E', 'report_nm': '감사보고서 (2023.12)', 'flr_nm': '삼정회계법인', 'rcept_dt': '20240328', 'rm': ''}.")

**Comment by josw123** [comment]
안녕하세요.

올려주신 코드에서 corp_code='00258999' 는 삼성전자서비스(센터)이며 삼성전자서비스의 경우에도 동일합니다.

삼성전자의 경우 corp_code="00126380"입니다.
```python

import dart_fss as dart

corp_list = dart.get_corp_list()
corps = corp_list.find_by_corp_name('삼성전자')

print(corps)
# [[00258999]삼성전자서비스,
#  [01345812]삼성전자서비스씨에스,
#  [00252074]삼성전자판매,
#  [00366997]삼성전자로지텍,
#  [00126380]삼성전자]
```
위와 같이 삼성전자로 검색하시는 경우 삼성전자가 포함된 모든 회사를 검색하게 됩니다.

만약 정확히 일치하는 회사만 검색하고 싶으시다면, 아래와 같이 검색을 진행하시면 되겠습니다.

```python
import dart_fss as dart

corp_list = dart.get_corp_list()
corp = corp_list.find_by_corp_name('삼성전자', exactly=True)
print(corp)
# [[00126380]삼성전자]
```

또는 코스피 상장사혹은 코스닥 상장사에서만 검색하고 싶으신 경우 아래와 같은 옵션을 주시면 됩니다.
```python
import dart_fss as dart

corp_list = dart.get_corp_list()
corp = corp_list.find_by_corp_name('삼성전자', market='YK')
print(corp)
# [[00126380]삼성전자]
```

**Comment by kkkim2015** [comment]
안녕하세요. 
말씀해 주신 삼성전자 corp_code로 해보니 제대로 작동하는 것을 확인했습니다! 
감사합니다
