### ISSUE TITLE
24년 9월 분기보고서 추출 문의

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [josw123/dart-fss#183]
안녕하세요. dart-fss 코드를 유용하게 사용하는 유저입니다.
먼저 제공해주시는 점 감사합니다. 이번 분기 보고서 추출하고자 하는데 아래와 같은 오류가 발생하는데요?

"raise FileNotFoundError('target does not exist')"
"raise BadZipFile("File is not a zip file")"

아래와 같은 코드로 진행하였습니다.
오류가 무엇인지 알 수 있을까요?

import dart_fss as dart

# Open DART API KEY 설정
api_key='개인코드'
dart.set_api_key(api_key=api_key)

# DART 에 공시된 회사 리스트 불러오기
corp_list = dart.get_corp_list()

# 삼성전자 검색
samsung = corp_list.find_by_corp_name('삼성전자', exactly=True)[0]

# 2012년부터 연간 연결재무제표 불러오기
fs = samsung.extract_fs(bgn_de='20230601', report_tp='quarter', separate=True)

# 재무제표 검색 결과를 엑셀파일로 저장 ( 기본저장위치: 실행폴더/fsdata )
fs.save()

**Comment by josw123** [comment]
안녕하세요.
버그리포트 감사합니다.

올려주신 코드와 동일한 코드로 테스트를 진행하였으나 
BadZipFile 오류가 발생하지 않아 추가적인 코드 및 환경을 올려주시면 감사하겠습니다.

**Comment by 0x68756d8616e6f69664** [comment]
재확인해보니 문제가 없어진 것 같습니다.
