### ISSUE TITLE
손익계산서 일부 값 누락 및 단위 오류 

### ISSUE THREAD

**Issue by paladinz67** [josw123/dart-fss#19]
안녕하십니까, 또 issue를 제기해서 죄송합니다.
혹시 제가 black list에 올라가 있지는 않은지요, ㅠㅠ

아래는 삼성전자의 재무제표를 일괄저장한 결과입니다.
당기순이익, 주당이익 등 일부 항목이 (20080101-20081231)을 포함하여 이전 회계연도의 값이 없습니다. dart.fss.or.kr에서 직접 다운받은 파일에는 값이 존재합니다.
[삼성전자.xlsx](https://github.com/josw123/dart-fss/files/3540061/default.xlsx)

![image](https://user-images.githubusercontent.com/31872335/63675497-e8ffce80-c823-11e9-96ee-13a0cb1a878d.png)

그리고, 주당이익이 특정 연도에서 크게 나옵니다. 아마  단위:백만원 적용 문제인 것 같습니다.
![image](https://user-images.githubusercontent.com/31872335/63675638-354b0e80-c824-11e9-8f33-22cfb796d590.png)

항상 빠른 대응에 감사드립니다.

**Comment by josw123** [comment]
안녕하세요.

1. 일부 항목 값이 누락되는 문제
일부 항목이 누락되는 문제의 경우, 기본 검색 방법으로는 값을 찾을수가 없어서 그렇습니다.
현재 dart-fss 라이브러리의 경우 기본적으로 2가지 방법으로 계정항목의 값을 추정합니다.

- (추정1)기존의 계정항목의 값과 일치여부
다트에 공시되는 재무제표의 경우 당해연도와 기존의 재무제표가 함께 공시됩니다.
이럴때 기존의 재무제표의 값을 기반으로 당해연도의 값을 추정하게 됩니다.
(예를들어 제40기의 매출액을 찾는 경우 제 39기와 동일한 값을 가지는 Row에 있는 값을 매출액으로 추정하는 것입니다.)
이는 재무제표 공시의 계정항목명이 보고서 마다 다르기 때문입니다.
(2009년: 기본주당이익 / 2008년: 기본주당순이익) 

- (추정2) 기존 계정항목명 찾기
(추정1)의 경우 2008~2009년, 혹은 재무제표 기준이 달라지는 2011년에 문제가 생기게 됩니다.
(자세한 사항은 [IFRS는 무엇인가?](https://m.blog.naver.com/kipfmanager/40162148201)를 참고하시면 감사하겠습니다.)
동일한 계정항목이라도 그 값이 전년도 공시와 달라지게 됩니다.
(예를들어 삼성전자의 경우 2010년 사업보고서, 2009년 사업보고서 공시)
이로 인해 값을 추정할 수 없는 문제가 생기게 됩니다.
이를 해결하기 위해 계정항목명의 일치여부를 조사하여 계정항목의 값을 추정하게 됩니다.
그러나 이는 한글의 정확한 일치여부를 검색하기 때문에 "기본주당이익", "기본주당순이익" 등과 같은 경우 검색에서 제외가 됩니다.

- (추정1), (추정2)의 문제를 해결하기 위해 [Dart-Fss-Classifier](https://github.com/josw123/dart-fss-classifier)를 설치하시면 자연어 검색을 통해 위와 같은 문제를 일부해결할 수 있습니다.

- 또한 [Dart-Fss-Classifier](https://github.com/josw123/dart-fss-classifier) 참고하셔서 추가적인 검색 알고리즘을 제작하시는 것도 좋은 방안으로 생각됩니다.

2. 주당이익이 연도에 따라 크게나오는 문제
이 문제는 해결가능한지 확인해 보도록 하겠습니다.
(DataFrame 변환과정에서 처리 가능할 것 같긴합니다.)

**Comment by paladinz67** [comment]
감사합니다.
Dart-Fss-Classifier 한번 이용해 보겠습니다.
