### ISSUE TITLE
docker에서 이상하게 작동.

### ISSUE THREAD

**Issue by shinhwas** [josw123/dart-fss#20]
안녕하세요. ShinhwaS입니다.
Docker에서 dataframe을 이상하게 계산하네요.
아래 코드를 수정한뒤 작동되네요.
`
		for key in df_count.keys().tolist():
			if regex_pass.search(' '.join(index[1])):
				pass
			elif df_count[key] <= 1:
				drop_columns.append(key)
`

`
		for key, count in df_count.items():
			if regex_pass.search(' '.join(key[1])):
				pass
			elif count <= 1:
				drop_columns.append(key)
`

업데이트하느라 수고하셨습니다.

**Comment by josw123** [comment]
버그 리포트 및 수정 감사합니다.
수정된 코드를 올리도록 하겠습니다.

**Comment by josw123** [comment]
수정된 코드 업로드하였습니다.
다시한번 감사드립니다.
