### ISSUE TITLE
xbrl.get_xbrl_from_file error 문제

### ISSUE THREAD

**Issue by jellyjel** [josw123/dart-fss#24]
xbrl파일을 직접 호출할때 nontype error가 납니다.
dart에서 다운받을 수 있는 ifrs.zip형태나 xbrl개별 파일로 해도 마찬가진데
dart_fss 패키지에서 웹 url 접근 형식만 가능한지요, ⠋ XBRL Loading 시간이 너무 많이 걸리네요.
답변 부탁드립니다. 감사합니다.

에러나는 코드입니다.
import dart_fss
dart_fss.xbrl.get_xbrl_from_file("/content/20200331002351_ifrs.zip")

에러 로그
 table = self.get_table_by_code(code)
---> 93         return table.to_DataFrame(lang=lang, show_class=False, show_concept=False, separator=False)
     94 
     95     def get_document_information(self, lang: str = 'ko') -> DataFrame:

AttributeError: 'NoneType' object has no attribute 'to_DataFrame'

**Comment by josw123** [comment]
안녕하세요.

### get_xbrl_from_file 오류에 관하여

dart-fss에서 제공하는 get_xbrl_from_file은 *.xbrl 파일 위치를 입력으로 받습니다.
즉, zip 파일의 경우 따로 압축을 해제한 후에 xbrl 파일을 불러 오시면 됩니다.
dart-fss 내부적으로도 dart_fss.utils.unzip 메소드를 이용하여 ifrs.zip 파일 압축해제 후 데이터를 처리하고 있습니다. 

> 주의사항
> 아래와 같이 ifrs.zip 파일 내부의 모든 파일을 압축해제 후 데이터 처리를 하셔야 합니다.
> 이는 ifrs.zip 파일 내부에는 XBRL 파일 뿐만아니라 XBRL Schema 등 다른 필수 정보가 포함되어 있기 때문입니다.

![fig1](https://user-images.githubusercontent.com/10247774/78827847-befbc500-7a1e-11ea-8e43-3ba5a98e4cae.png)

```python
import dart_fss as dart

# 절대 주소 및 상대 주소 모두 사용가능합니다
xbrl = dart.xbrl.get_xbrl_from_file(r"C:\\Users\\사용자명\\Desktop\\20200331002351_ifrs\\00244455_2020-03-30.xbrl")
```

### XBRL 로딩 시간에 관하여

XBRL 분석에는 ifrs.zip에 첨부된 파일 뿐만 아니라 web에 공개된 정보들이 필요하기 때문입니다.

ifrs.zip 파일에는 각각 개별 기업의 회계 정보가 들어 있습니다. 그러나 XBRL 분석을 위해서는 공통적인 회계 계정에 관한 정보가 필요합니다.

DART에서는 이러한 공통적인 정보를 ifrs.zip에 첨부하지 않고, 온라인을 통해 공개해 놓았습니다.

좀더 자세히 말하자면, XBRL 분석에는 XBRL 구조 및 회계정보에 관한 XBRL Taxonomy가 필요합니다. 
이러한 Taxnomy는 국제회계기준 IFRS와 한국회계기준 K-IFRS 모두 필요하고, 각각의 회사가 공통적으로 사용하는 항목이기 때문에 zip파일에 첨부되어 있지 않고, 온라인상에 공개되어 있습니다.

이로 인하여 XBRL 분석중에는 분석에 필요한 추가적인 Taxonomy 파일을 온라인에서 추가로 다운로드 받기 때문에 분석시간이 오래 걸리게 됩니다.

> 예를들어 http://dart.fss.or.kr/Resource/Taxonomy/ifrs/2019-10-01/dart_entry_point_2019-10-01.xsd 파일과 같이 추가적인 Taxonomy 파일을 다운로드하여 분석합니다.

XBRL Loading 시간 단축에 관해서는 한번 방법을 찾아보도록 하겠습니다.
