### ISSUE TITLE
Download 초반에서 멈추는 문제

### ISSUE THREAD

**Issue by life-is-long-short** [josw123/dart-fss#3]
```samsung_electronics.get_financial_statement(start_dt='20120101')``` 를 실행하면 31kb까지 받아진 이후에 멈춰버립니다.

Download: 31.0KB [00:01, 17.8KB/s]

**Comment by josw123** [comment]
화면에 표시되는 31kb는 각각 회사의 XBRL 파일의 크기입니다.

그러나 실제로 이 XBRL 파일을 처리하기 위해서는 IFRS 관련 파일들을 추가로 다운로드해야 됩니다. 
이는 Arelle 라이브러리에서 자동으로 처리해주며, 이후 IFRS 파일 과 XBRL 파일을 합쳐 재무제표를 분석하게 됩니다.

**그런데 최초 Arelle 라이브러리 실행시 캐시된 IFRS 데이터가 없기 때문에, 분석하는데 좀 오랜 시간이 걸리게 됩니다. 그렇기 만약 다운로드 된 이후 오류가 발생하지 않는다면, 좀 기다리시면 이후 작업이 진행됩니다.**

이후 Arelle 라이브러리는 IFRS 데이터를 특정폴에 관련 정보를 캐시해 놓기 때문에, 최초실행시 보다는 빠른 분석이 진행됩니다.

Arelle 라이브러리 Cache 폴더
Linux: ~/.config/arelle
macOS: ~/Library/Application Support/Arelle
windows: C:/Users/swjo/AppData/Loca/Arelle (또는 Arelle package 내부 폴더)
