### ISSUE TITLE
Could not find consolidated financial statements

### ISSUE THREAD

**Issue by wjh744** [josw123/dart-fss#33]
재무재표추출 corp.extract_fs를 이용해서 대한약품 이란 회사의 재무재표를 추출해보았는데요. Could not find consolidated financial statements 라는 오류가 뜹니다. 뭐가 문제 인지 모르겠는데 도와주세요.

**Comment by josw123** [comment]
안녕하세요.

**NotFoundConsolidated 오류는 연결재무제표가 없을시 발생하는 오류 입니다.**
이는 대한약품의 **지배·종속관계가 없기 때문에 연결재무제표를 공시할 필요 없이 별도재무제표만 공시**하면 됩니다.

![image](https://user-images.githubusercontent.com/10247774/88013003-45fc2580-cb56-11ea-8c97-79342c01bfef.png)

이러한 경우 extract_fs 함수에서는 NotFoundConsolidated 오류(Could not find consolidated financial statements)가 발생하게 됩니다.

별도재무제표의 경우 공시된 정보가 있으므로 추출이 가능하며, 만약 별도재무제표를 추출하시려면  아래와 같이 separate 옵션을 True로 설정하시면 됩니다.(default: False)
```
fs = corp.extract_fs(bgn_de='20120101', separate=True) 
```
추출 함수에 관련된 사항은 [dart-fss 문서의 일괄 추출](https://dart-fss.readthedocs.io/en/latest/dart_fs.html#dart_fss.fs.extract)을 참고하시면 되겠습니다.

또한 오류에 관한 자세한 사항은 [dart-fss 문서의 오류](https://dart-fss.readthedocs.io/en/latest/dart_errors.html)를 참고하시면 되겠습니다.
