### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by daeunk0710** [josw123/dart-fss#37]
안녕하세요, 라이브러리 잘 사용하고 있습니다.
재무제표 추출 중 에러 발생해서 리포트 드립니다.
단위가 엔인 기업의 경우 예외처리가 되지 않은 것 같아요!

감사합니다.

RuntimeError: An error occurred while fetching or analyzing {'rcp_no': '20200120000265', 'corp_code': '01041828', 'corp_name': 'JTC', 'stock_code': '950170', 'corp_cls': 'K', 'report_nm': '[기재정정]사업보고서 (2019.02)', 'flr_nm': 'JTC', 'rcept_dt': '20200120', 'rm': '연'}.

**Comment by josw123** [comment]
안녕하세요.

엔화의 경우도 추가하도록 하겠습니다.

버그 리포트 감사합니다.
