### ISSUE TITLE
10년 이상 재무 조회 시 오류

### ISSUE THREAD

**Issue by an14700** [josw123/dart-fss#40]
라이브러리 잘 사용하고 있습니다.  감사합니다. 

아래와 같이 10년 이상의 정보를 조회하면 연도가 잘 못 되는 오류가 발생합니다. 
fs = samsung.extract_fs(bgn_de='20000101', end_de='20201231')

아래와같이 2009년 데이터가 두개 존재하는 것을 볼 수 있습니다. 
2009년 자료는 10년 이하 데이터 조회 시 정상 조회됩니다.

20110101 | 20101231 | 20091231 | 20090101 | 20081231
-- | -- | -- | -- | --

위 코드로 조회한 삼성전자 20년 재무 자료입니다. 
[00126380_annual.xlsx](https://github.com/josw123/dart-fss/files/5073009/00126380_annual.xlsx)

**Comment by josw123** [comment]
안녕하세요.

2009년 데이터가 두개(2009년 12월 31일 / 2009년 01월 01일)가 존재하는 것은 삼성전자의 국제회계기준(IFRS) 도입에 따른 것입니다.  

[IFRS 도입 관련 기사](https://www.mk.co.kr/news/business/view/2010/05/280193/) 

이로 인해 아래와 같이 2010년 연결재무제표에는 전환일(2009년 01월 01일)이 표시되어 있으며, [dart-fss](https://github.com/josw123/dart-fss)에서는 전환일을 표함한 모든 데이터를 추출하기 때문입니다.

![image](https://user-images.githubusercontent.com/10247774/90225712-c3ad0b80-de4c-11ea-8c1e-f84b6c2eb964.png)

또한 2011년의 경우에도 제 43 기초 정보가 포함된 데이터가 공시되었기 때문에 관련 정보를 추출하고 있습니다. (이는 K-IFRS가 도입되었기 때문으로 생각됩니다.)

![image](https://user-images.githubusercontent.com/10247774/90226086-6cf40180-de4d-11ea-9f74-91b1a60f9f3c.png)

추가적으로 [dart-fss](https://github.com/josw123/dart-fss)에서는 최신 정보에서부터 정보를 조회하여 재무제표를 추출하며, 2010년 이하 데이터 조회시에는 위의 그림과 같이 2010년 공시데이터가 포함되어 있지 않기 때문에 2009년 01월 01일(기초)데이터가 추출되지 않습니다.
