### ISSUE TITLE
제무제표 축출시 부호(+,-), 일부항목 확인 부탁 드립니다.

### ISSUE THREAD

**Issue by nowdob** [josw123/dart-fss#44]
안녕하세요 유용한 라이브러리를 만들어 주셔서 감사 드립니다.
제무제표를 분석을 위해 아래와 같이 장기간 데이터 축출해 보았는데요.
일부 항목 축출 및 금액 부호(+,-)가 다른 것 같아 확인 좀 부탁 드립니다.
GS리테일, 카카오(현금흐름표 부호 다름)에 대해 테스트 해보았습니다. 
GS리테일 축출 자료, DART 조회 화면 정리해 보았습니다.  

**- 실행코드**
# GS리테일
corp_code = "007070"
fs = dart.fs.extract(corp_code=corp_code, bgn_de='20110101')
fs.save()

**- 축출 데이터(dart-fss)**
  1. 연결 포괄손익계산서
![image](https://user-images.githubusercontent.com/57924795/91539155-dd257b80-e953-11ea-86c9-8d48e0a405d2.png)
  2. 연결 현금흐름표 
![image](https://user-images.githubusercontent.com/57924795/91539762-c7fd1c80-e954-11ea-9dd1-a977f73e4b90.png)

**- DART자료**
  1. 연결 포괄손익계산서
![image](https://user-images.githubusercontent.com/57924795/91539234-f9291d00-e953-11ea-830b-f63db25bc594.png)
  2. 연결 현금흐름표
![image](https://user-images.githubusercontent.com/57924795/91539793-d6e3cf00-e954-11ea-9221-59811af4241c.png)

- 카카오 부호 다름 예시(추가)
![image](https://user-images.githubusercontent.com/57924795/91540184-66897d80-e955-11ea-9e75-7a78eb923a65.png)
![image](https://user-images.githubusercontent.com/57924795/91540348-a3557480-e955-11ea-954d-8e62fadb2385.png)

**Comment by josw123** [comment]
안녕하세요.

확인해 본 결과 올려주신 것과 같이 재무제표 정보에 대하여 XBRL 파일에서 추출된 재무제표에서는 +로 표시되나, 온라인 공시시 -로 표시되는 문제가 있는 것을 확인하였습니다.
관련 사항은 최대한 빠르게 수정하여 업데이트 하도록 하겠습니다.

또한 일부 재무제표상의 정보가 추출되지 않는 것은 dart-fss 라이브러리가 사업보고서상에 첨부된 감사보고서를 기반으로 재무제표를 추출하기 때문입니다.

아래는 48기 사업보고서상에 첨부된 감사보고서의 내용이며, 여기에는 2016년 데이터가 없습니다.

![image](https://user-images.githubusercontent.com/10247774/91673036-f2c1bd80-eb6c-11ea-99f6-54f8e7c524d1.png)

이에 반하여 48기 사업보고서상의 재무제표에는 2016년 데이터가 첨부되어 있습니다.

![image](https://user-images.githubusercontent.com/10247774/91673044-fa816200-eb6c-11ea-8cef-1319a217030b.png)

이로 인해 dart-fss 라이브러리에서는 우선적으로 감사보고서의 재무제표 추출이 가능한 경우 사업보고서 본문의 재무제표 추출을 진행하지 않습니다.

대신 아래와 같이 47기에 포함된 재무제표를 추출하게 됩니다.

![image](https://user-images.githubusercontent.com/10247774/91673102-49c79280-eb6d-11ea-9a30-78508738393c.png)

그러나 첨부된 그림을 보시면 47기에 첨부된 연결포괄손익계산서 상에서는 "매출채권및기타채권 손상차손",  "금융원가"와 동일명칭의 과목이 없으므로 데이터를 추출하지 못하게 됩니다.
(과목명이 동일한 경우나, 데이터 비교를 통해 같은 과목으로 추정되는 경우에만 데이터를 추출하게 됩니다.)

이와 관련된 사항은 추가적으로 고려해 보고 업데이트를 진행하도록 하겠습니다.

**Comment by nowdob** [comment]
안녕하세요

빠른 확인과 명확한 설명에 감사 드립니다.
친절하게 답변해 주셔서 라이브러리 동작에 대해서 보다 잘 이해할 수 있었습니다.


2020년 8월 31일 (월) 오전 9:39, Sungwoo Jo <notifications@github.com>님이 작성:
