### ISSUE TITLE
'LG화학' 당기순이익(ifrs-full_ProfitLoss) 일부 추출 되지 않음

### ISSUE THREAD

**Issue by noindexing** [josw123/dart-fss#45]
안녕하세요. 좋은 라이브러리 만들어 주셔서 감사합니다.

'LG화학' 종목의 경우 [20190101-20191231] 기간 처럼 full year의 경우 당기순이익 값이 추출되나
[20200101-20200630] 처럼 반기/분기 보고서의 경우 nan 값으로 추출됩니다.

추출에 사용한 code snippet 입니다.
```
fs = corp.extract_fs(bgn_de=begin, fs_tp=('is',), report_tp='quarter', lang='ko', separator=False)
fs_is = fs.show('is')  # 연결손익계산서
print('is', fs_is)
```
현재 Dart-Fss-Classifier를 같이 사용하고 있습니다.
제가 제대로 사용하고 있지 않은지, 혹은 수정 방향에 가이드를 알려 주시면 감사하겠습니다.

**Comment by josw123** [comment]
안녕하세요.

데이터를 확인해보니,  label_ko가 다르기 때문에 추출되지 않은 것으로 보입니다.
("순이익" / "반기순이익"/ "분기순이익") 

이와 관련된 버그는 추출 알고리즘 수정을 통해 업데이트 하도록 하겠습니다.
