### ISSUE TITLE
비상장주식 find_by_stock_code으로 search

### ISSUE THREAD

**Issue by SeunghyeonTonyYu** [josw123/dart-fss#53]
안녕하세요 dart_fss를 사용하다 비상장기업 조회를 하다 issue가 생겼습니다.

예를 들어 "차이나하오란리사이클링유한공사[900090]"이라는 상장폐지된 기업을 종목코드를 이용하여 검색하려고 하면 아무 결과도 나오지 않습니다.

```python
import dart_fss as dart
api_key = '364b0537dda8f51af24ec751fb3fa8bf8ecf5002'
dart.set_api_key(api_key=api_key)
crp_list = dart.get_corp_list()
crp_list.find_by_stock_code('900090')
```

반면, 회사이름으로 검색하면 정상적으로 나옵니다.

```python
crp_list.find_by_corp_name('차이나하오란리사이클링유한공사')
```
```bash
[[00790121]차이나하오란리사이클링유한공사]
```

crp_list가 상장된 기업만 filter 된거라면 이름으로 검색하면 안 나와야할 것이고, 비상장 기업도 포함했다면 종목코드로 검색이 되어야할텐데 종목코드로 비상장 기업을 검색하는 방법이 있을까요?

감사합니다.

**Comment by josw123** [comment]
안녕하세요.

get_corp_list를 통해 반환되는 기업리스트에는 DART에 공시되는 모든 회사가 포함되어 있습니다.
그러므로 find_by_corp_name을 이용한 기업 검색시 비상장 기업도 검색이 가능합니다.
(옵션을 통해 상장 기업만 조회도 가능합니다. 자세한 사항은 [기업정보검색](https://dart-fss.readthedocs.io/en/latest/dart_corp.html) 을 참고하시면 됩니다)

그러나 find_by_stock_code를 이용한 검색시에는 상장된 기업 리스트에서 조회하도록 구현되어 있습니다.
그러므로 현재 find_by_stock_code를 이용한 검색시에는 비상장기업이 조회가 되지 않습니다.

다음버전에는 find_by_stock_code 함수에 상장폐지된 기업도 조회 가능한 옵션을 추가하도록 하겠습니다.
