### ISSUE TITLE
extract_fs함수의 반기보고서 재무제표 데이터 불러오기 에러 공유

### ISSUE THREAD

**Issue by BigBig-Nose** [josw123/dart-fss#85]
dangsa = corp_list.find_by_corp_name("삼성전자", exactly=True)[0]
fs = dangsa.extract_fs(bgn_de = 20200101, report_tp= "half")

안녕하세요. 라이브러리를 만들어주셔서 너무 감사드립니다. 너무나 잘 사용하고 있습니다.
며칠 전 까지는 위 함수를 이용했을 때, 재무제표 내용이 잘 불러들여와서 저장이 됐었는데, 현재는 반기에 대해서는 에러가 발생합니다. ( "Dart Scraper"에서도 동일한 에러가 발생하는 듯 하네요.)
![화면 캡처 2021-09-01 010404](https://user-images.githubusercontent.com/89759613/131537211-41008289-b06c-49fd-9c26-325316630dac.jpg)

에러메시지 전체는 아래와 같습니다. 이 에러 수정이 가능할까요? ㅠㅠ

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-1038c97b72d9> in <module>
      1 dangsa = corp_list.find_by_corp_name("삼성전자", exactly=True)[0]
----> 2 fs = dangsa.extract_fs(bgn_de = 20200101, report_tp= "half")

C:\ProgramData\Anaconda3\lib\site-packages\dart_fss\corp\corp.py in extract_fs(self, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
    231 
    232          """
--> 233         return extract(self.corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)

C:\ProgramData\Anaconda3\lib\site-packages\dart_fss\fs\extract.py in extract(corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
   1323             msg = 'Unexpected Error'
   1324         e.args = (*e.args, msg, )
-> 1325         raise e
   1326     finally:
   1327         dart.utils.spinner.spinner_enable = True

C:\ProgramData\Anaconda3\lib\site-packages\dart_fss\fs\extract.py in extract(corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
   1284 
   1285                     else:
-> 1286                         nstatements = analyze_report(report=report,
   1287                                                      fs_tp=fs_tp,
   1288                                                      separate=separate,

C:\ProgramData\Anaconda3\lib\site-packages\dart_fss\fs\extract.py in analyze_report(report, fs_tp, separate, lang, separator, dataset)
   1146     year = int(report.rcept_dt[:4])
   1147     if year > 2011 and dataset == 'xbrl':
-> 1148         xbrl = report.xbrl
   1149     else:
   1150         xbrl = None

C:\ProgramData\Anaconda3\lib\site-packages\dart_fss\filings\reports.py in __getattr__(self, item)
     93         else:
     94             error = "'{}' object has no attribute '{}'".format(type(self).__name__, item)
---> 95             raise AttributeError(error)
     96 
     97     def _get_report(self):

AttributeError: ("'Report' object has no attribute 'xbrl'", "An error occurred while fetching or analyzing {'rcp_no': '20210817001416', 'corp_code': '00126380', 'corp_name': '삼성전자', 'stock_code': '005930', 'corp_cls': 'Y', 'report_nm': '반기보고서 (2021.06)', 'flr_nm': '삼성전자', 'rcept_dt': '20210817', 'rm': ''}.")

**Comment by josw123** [comment]
안녕하세요.

올려주신 문제는, dart 홈페이지가 개편되면서 생기는 문제입니다.
이 버그는 요번주 내로 수정되어 배포될 예정입니다.
