### ISSUE TITLE
특정 기업들 재무제표 에서 발생하는 에러 확인

### ISSUE THREAD

**Issue by gangilseo** [josw123/dart-fss#88]
현재 몇몇 기업에서 Report object has no attribute 'attached_reports' 라는 에러가 발생하며 재무데이터 추출이 이루어지지 않는 상황이 발생하고있습니다. (한국주강, 예스24 etc.)

재무데이터를 읽어올떄 dart 원 데이터의 문제가 아닐까 생각됩니다만, 혹 이 부분을 해결할 수 있는 방법이 있는지 확인해주시면 감사하겠습니다.

**Comment by josw123** [comment]
안녕하세요.
답변이 늦은점 죄송합니다.
본업과 개인적인 사정으로 인해 시간이 부족하여 이제 답변드립니다.

본 문제는 DART 홈페이지 개편으로 인해 발생하는 문제로 생각되며 [v0.3.14](https://github.com/josw123/dart-fss/releases/tag/v0.3.14) 에서 Fix되었습니다.

아래와 같이 업데이트 후 사용해 보시기 바랍니다.
```bash
pip install dart-fss -U
```
