### ISSUE TITLE
삼성전자 2021년 6월 기준 xbrl 원본 추출 불가 

### ISSUE THREAD

**Issue by Unfinishedgod** [josw123/dart-fss#89]
안녕하세요. dart_fss 잘 사용하고 있습니다.

dart.filings.search() 함수를 사용해 삼성전자의 6월 반기 보고서의 xbrl 원본을 추출하려는데 다음과 같은 에러가 발생 합니다. 

 - ``` AttributeError: 'Report' object has no attribute 'xbrl' ```

그러나 해당 반기보고서의 다운로드 항목을 보면 xbrl원본 zip이 있긴 한데 어떤 이유로 에러가 발생하는지 여쭤보고자 남깁니다. 

 - [삼성전자 2021년 6월 반기 보고서 ](https://dart.fss.or.kr/pdf/download/main.do?rcp_no=20210817001416&dcm_no=8181127)

자세한 정보는 다음과 같습니다. 
- rcp_no:20210817001416 
- corp_code:00126380 
- corp_name:삼성전자 
- stock_code:005930 
- corp_cls:Y 
- report_nm:반기보고서 (2021.06) 
- flr_nm:삼성전자 
- rcept_dt:20210817

**Comment by josw123** [comment]
안녕하세요.

```python
import dart_fss as dart

print(dart.__version__)
```
의 출력결과가 0.3.14이신가요?

최근 DART 홈페이지 개편으로 인해 최신 버전인 v0.3.14을 제외한 버전에서는 올려주신 내용과 같은 버그가 발생하게 됩니다.

```sh
pip install -U dart-fss
```
또는
```sh
pip install dart-fss==0.3.14
```
를 통해 최신 버전으로 업데이트 후 실행하시면 아래와 같이 정상적으로 동작하겠습니다.
 
![image](https://user-images.githubusercontent.com/10247774/133401203-5f86f8bd-b3b6-4f3f-8db0-b97d97f74444.png)
