### ISSUE TITLE
[첨부정정]이 된 사업보고서 읽기 문제

### ISSUE THREAD

**Issue by youngwoo-michael-kim** [josw123/dart-fss#92]
BNK금융지주의 사업보고서를 읽으려는데, 연결재무제표를 읽을 수 없다는 에러가 나옵니다.
 'Could not find consolidated financial statements'

'[첨부정정]사업보고서' 라는 수정내역이 문제인 거 같아서요
extract 함수에서, report_list에서 1번째 인덱스를 읽는 방식으로 해결하고 있는데
혹시 이것보다 간결한 해결방법이 없을까요..?

`
corp = corp_list.find_by_corp_name('BNK금융지주', exactly=True)[0]

fs = corp.extract_fs(bgn_de='20210101')

Annual reports:   0%|          | 0/1 [00:00<?, ?report/s]C:\Users\kimin\Desktop\ElegantRL-master\dart_api\venv\lib\site-packages\dart_fss\fs\extract.py:1340: RuntimeWarning: Unable to extract financial statements: {'rcp_no': '20210517001446', 'corp_code': '00858364', 'corp_name': 'BNK금융지주', 'stock_code': '138930', 'corp_cls': 'Y', 'report_nm': '[첨부정정]사업보고서 (2020.12)', 'flr_nm': 'BNK금융지주', 'rcept_dt': '20210517', 'rm': '연'}.
  warnings.warn(warnings_text, RuntimeWarning)
Annual reports: 100%|██████████| 1/1 [00:03<00:00,  3.00s/report]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\kimin\Desktop\ElegantRL-master\dart_api\venv\lib\site-packages\dart_fss\corp\corp.py", line 233, in extract_fs
    return extract(self.corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
  File "C:\Users\kimin\Desktop\ElegantRL-master\dart_api\venv\lib\site-packages\dart_fss\fs\extract.py", line 1396, in extract
    raise e
  File "C:\Users\kimin\Desktop\ElegantRL-master\dart_api\venv\lib\site-packages\dart_fss\fs\extract.py", line 1372, in extract
    raise NotFoundConsolidated('Could not find consolidated financial statements')
dart_fss.errors.errors.NotFoundConsolidated: ('Could not find consolidated financial statements', "An error occurred while fetching or analyzing {'rcp_no': '20210517001446', 'corp_code': '00858364', 'corp_name': 'BNK금융지주', 'stock_code': '138930', 'corp_cls': 'Y', 'report_nm': '[첨부정정]사업보고서 (2020.12)', 'flr_nm': 'BNK금융지주', 'rcept_dt': '20210517', 'rm': '연'}.")
`

**Comment by josw123** [comment]
안녕하세요.

일부 버그가 있어 이 문제는 다음 버전에 수정되어 올라갈 예정입니다.
(원래는 문제없이 검색되어야 정상이나 지금 버전에 버그가 있어 검색되지 않는 문제가 발생합니다)

지금 버전에서 가장 간단한 해결방법은 아래와 같이  검색종료일자를 지정하여 검색하는 방법입니다.

```python
fs = corp.extract_fs(bgn_de='20210101', end_de='20210501')
```
