### ISSUE TITLE
분기 보고서 추출 관련 문의

### ISSUE THREAD

**Issue by Discipline-Always** [josw123/dart-fss#95]
안녕하세요?
프로그램 너무 감사히 잘 쓰고 있습니다.

분기 추출 관련해서 문의 드리고 싶어 글 올립니다.
현행은 손익계산서가 quarter옵션으로 추출될 때 

3분기 해당	2분기 해당	4분기 누적	3분기 누적	2분기 누적	1분기 누적(해당)

이런 구조로 추출돼서, 
해당 분기 기간의 실적을 구분하기가 다소 까다로운 것 같습니다. 
시계열이 길어질수록 엑셀로 헤더를 빼내는 게 번거로워지고요.

혹시 분기추출 옵션의 경우에는 손익계산서가 각 분기 '해당 실적만' 추출되게 하거나,
아니면 '누적만' 추출되게 하는 건 어떻게 생각하시는지 여쭙습니다.
둘 중에 하나만 있으면 엑셀로 처리하기가 간편할 것 같아서요.

**Comment by josw123** [comment]
안녕하세요.

보내주신 의견을 고려하여 다음번 버전에 적용해 보도록 하겠습니다.

**Comment by Discipline-Always** [comment]
> 안녕하세요.
> 
> 보내주신 의견을 고려하여 다음번 버전에 적용해 보도록 하겠습니다.

감사합니다.
코드 잠깐 살펴봤는데 정말 체계적이고 대단하십니다.
