### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by SMAIL102938** [josw123/dart-fss#96]
에이치피에스피, 다비치안경체인, 트리노드, 디쉐어, 더블미디어, 미코세라믹스 등 10개의 건에 대해서 코드를 돌렸는데 모두 runtime error가 나옵니다ㅜ.. 혹시 도와주실 수 있나요?

+ 제가 생각했을때는 사업보고서가 있는 삼성전자, SK하이닉스 등은 밑에 같은 dart.fs.extract이 되지만, 감사보고서가 있는 에이치피에스피, 트리노드, 다비치안경체인 등은 검색이 안되는 듯 싶습니다 수정가능하신가요?ㅜㅜㅜ

for name in ['다비치안경체인']:
  company = corp_list.find_by_corp_name(name, exactly=True)[0]
  corp_code = str(company.corp_code)
  FS = dart.fs.extract(corp_code=corp_code, bgn_de='20210101', report_tp='annual', separate=True)

 ‐------------------------------------------

Annual reports: 100%
1/1 [00:02<00:00, 2.91s/report]
/usr/local/lib/python3.7/dist-packages/dart_fss/fs/extract.py:1340: RuntimeWarning: Unable to extract financial statements: {'rcp_no': '20210405001095', 'corp_code': '01336726', 'corp_name': '다비치안경체인', 'stock_code': '', 'corp_cls': 'E', 'report_nm': '감사보고서 (2020.12)', 'flr_nm': '신승회계법인', 'rcept_dt': '20210405', 'rm': ''}.
  warnings.warn(warnings_text, RuntimeWarning)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-ce35c0188ef8> in <module>()
      2   company = corp_list.find_by_corp_name(name, exactly=True)[0]
      3   corp_code = str(company.corp_code)
----> 4   FS = dart.fs.extract(corp_code=corp_code, bgn_de='20210101', report_tp='annual', separate=True)

2 frames
/usr/local/lib/python3.7/dist-packages/dart_fss/fs/extract.py in extract(corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
   1394             msg = 'Unexpected Error'
   1395         e.args = (*e.args, msg, )
-> 1396         raise e
   1397     finally:
   1398         dart.utils.spinner.spinner_enable = True

/usr/local/lib/python3.7/dist-packages/dart_fss/fs/extract.py in extract(corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
   1372             raise NotFoundConsolidated('Could not find consolidated financial statements')
   1373 
-> 1374         statements = drop_empty_columns(statements)
   1375         label_df = drop_empty_columns(label_df)
   1376 

/usr/local/lib/python3.7/dist-packages/dart_fss/fs/extract.py in drop_empty_columns(df, label_df)
   1160 def drop_empty_columns(df: Dict[str, DataFrame], label_df: bool = False) -> Dict[str, DataFrame]:
   1161 
-> 1162     for tp in df:
   1163         df_tp = df[tp]
   1164         if df_tp is None:

TypeError: ("'NoneType' object is not iterable", "An error occurred while fetching or analyzing {'rcp_no': '20210405001095', 'corp_code': '01336726', 'corp_name': '다비치안경체인', 'stock_code': '', 'corp_cls': 'E', 'report_nm': '감사보고서 (2020.12)', 'flr_nm': '신승회계법인', 'rcept_dt': '20210405', 'rm': ''}.")

**Comment by josw123** [comment]
안녕하세요.

올려주신 버그는 #92 와 연관된 버그로 생각되며

 a3a6567391c421178a1388147980039d7411e3ba 에서 Fix되었습니다.

이는 다음 버전에 적용되어 배포될 예정이며

만약 당장 사용이 필요하시다면 develop branch를 clone하여 사용하시면 되겠습니다.
